import Head from 'next/head'
import Header from '../components/Header'
import Posts from '../components/Posts'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>ATG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />
        <Posts />

    </div>
  )
}
